var uagent=navigator.userAgent.toLowerCase(),is_safari=uagent.indexOf("safari")!=-1||navigator.vendor=="Apple Computer, Inc.",is_opera=uagent.indexOf("opera")!=-1,is_ie=uagent.indexOf("msie")!=-1&&!is_opera&&!is_safari,is_ie4=is_ie&&uagent.indexOf("msie 4.")!=-1,is_win=uagent.indexOf("win")!=-1||uagent.indexOf("16bit")!=-1,ua_vers=parseInt(navigator.appVersion),ie_range_cache="",list_open_tag="",list_close_tag="",listitems="",bbtags=[],rus_lr2="\u0415-\u0435-\u041e-\u043e-\u0401-\u0401-\u0401-\u0401-\u0416-\u0416-\u0427-\u0427-\u0428-\u0428-\u0429-\u0429-\u042a-\u042c-\u042d-\u042d-\u042e-\u042e-\u042f-\u042f-\u042f-\u042f-\u0451-\u0451-\u0436-\u0447-\u0448-\u0449-\u044d-\u044e-\u044f-\u044f".split("-"),
lat_lr2=("/E-/e-/O-/o-\u042bO-\u042bo-\u0419O-\u0419o-\u0417H-\u0417h-\u0426H-\u0426h-\u0421H-\u0421h-\u0428H-\u0428h-\u044a"+String.fromCharCode(35)+"-\u044c"+String.fromCharCode(39)+"-\u0419E-\u0419e-\u0419U-\u0419u-\u0419A-\u0419a-\u042bA-\u042ba-\u044bo-\u0439o-\u0437h-\u0446h-\u0441h-\u0448h-\u0439e-\u0439u-\u0439a-\u044ba").split("-"),rus_lr1="\u0410-\u0411-\u0412-\u0413-\u0414-\u0415-\u0417-\u0418-\u0419-\u041a-\u041b-\u041c-\u041d-\u041e-\u041f-\u0420-\u0421-\u0422-\u0423-\u0424-\u0425-\u0425-\u0426-\u0429-\u042b-\u042f-\u0430-\u0431-\u0432-\u0433-\u0434-\u0435-\u0437-\u0438-\u0439-\u043a-\u043b-\u043c-\u043d-\u043e-\u043f-\u0440-\u0441-\u0442-\u0443-\u0444-\u0445-\u0445-\u0446-\u0449-\u044a-\u044b-\u044c-\u044c-\u044f".split("-"),
lat_lr1=("A-B-V-G-D-E-Z-I-J-K-L-M-N-O-P-R-S-T-U-F-H-X-C-W-Y-Q-a-b-v-g-d-e-z-i-j-k-l-m-n-o-p-r-s-t-u-f-h-x-c-w-"+String.fromCharCode(35)+"-y-"+String.fromCharCode(39)+"-"+String.fromCharCode(96)+"-q").split("-");function setFieldName(a){a!=selField&&(selField=a)}function emoticon(a){doInsert(" "+a+" ","",!1)}function pagebreak(){doInsert("{PAGEBREAK}","",!1)}function simpletag(a){doInsert("["+a+"]","[/"+a+"]",!0)}
function tag_url(){var a=get_sel(eval("fombj."+selField));a||(a="My Webpage");DLEprompt(text_enter_url,"http://",dle_prompt,function(b){DLEprompt(text_enter_url_name,a,dle_prompt,function(a){doInsert("[url="+b+"]"+a+"[/url]","",!1);ie_range_cache=null})})}
function tag_leech(){var a=get_sel(eval("fombj."+selField));a||(a="My Webpage");DLEprompt(text_enter_url,"http://",dle_prompt,function(b){DLEprompt(text_enter_url_name,a,dle_prompt,function(a){doInsert("[leech="+b+"]"+a+"[/leech]","",!1);ie_range_cache=null})})}function tag_youtube(){var a=get_sel(eval("fombj."+selField));a||(a="http://");DLEprompt(text_enter_url,a,dle_prompt,function(a){doInsert("[media="+a+"]","",!1);ie_range_cache=null})}
function tag_flash(){var a=get_sel(eval("fombj."+selField));a||(a="http://");DLEprompt(text_enter_flash,a,dle_prompt,function(a){DLEprompt(text_enter_size,"425,264",dle_prompt,function(d){doInsert("[flash="+d+"]"+a+"[/flash]","",!1);ie_range_cache=null})})}function tag_list(a){list_open_tag=a=="ol"?"[ol=1]\n":"[list]\n";list_close_tag=a=="ol"?"[/ol]":"[/list]";listitems="";(a=get_sel(eval("fombj."+selField)))||(a="");insert_list(a)}
function insert_list(a){DLEprompt(text_enter_list,a,dle_prompt,function(a){a!=""?(listitems+="[*]"+a+"\n",insert_list("")):listitems&&(doInsert(list_open_tag+listitems+list_close_tag,"",!1),ie_range_cache=null)},!0)}
function tag_image(){var a=get_sel(eval("fombj."+selField));a||(a="http://");DLEprompt(text_enter_image,a,dle_prompt,function(a){DLEprompt(img_title,image_align,dle_prompt,function(d){d==""?doInsert("[img]"+a+"[/img]","",!1):d=="center"?doInsert("[center][img]"+a+"[/img][/center]","",!1):doInsert("[img="+d+"]"+a+"[/img]","",!1);ie_range_cache=null},!0)})}
function tag_video(){var a=get_sel(eval("fombj."+selField));a||(a="http://");DLEprompt(text_enter_url,a,dle_prompt,function(a){doInsert("[video="+a+"]","",!1);ie_range_cache=null})}function tag_audio(){var a=get_sel(eval("fombj."+selField));a||(a="http://");DLEprompt(text_enter_url,a,dle_prompt,function(a){doInsert("[audio="+a+"]","",!1);ie_range_cache=null})}
function tag_email(){var a=get_sel(eval("fombj."+selField));a||(a="");DLEprompt(text_enter_email,"",dle_prompt,function(b){DLEprompt(email_title,a,dle_prompt,function(a){doInsert("[email="+b+"]"+a+"[/email]","",!1);ie_range_cache=null})})}
function doInsert(a,b,d){var c=eval("fombj."+selField);c.focus();if(ua_vers>=4&&is_ie&&is_win){if(c.isTextEdit){var c=document.selection,e=ie_range_cache?ie_range_cache:c.createRange();if((c.type=="Text"||c.type=="None")&&e!=null)b!=""&&e.text.length>0?a+=e.text+b:d&&(a+=e.text+b),e.text=a}else c.value+=a+b;e.select();ie_range_cache=null}else if(c.selectionEnd){var h=c.selectionStart,e=c.scrollTop,g=c.selectionEnd,i=c.value.substring(0,h),f=c.value.substring(h,g),g=c.value.substring(g,c.textLength);
d||(f="");f=a+f+b;c.value=i+f+g;a=h+f.length;c.selectionStart=a;c.selectionEnd=a;c.scrollTop=e}else c.value+=a+b;return!1}
function ins_color(){document.getElementById(selField).focus();is_ie&&(document.getElementById(selField).focus(),ie_range_cache=document.selection.createRange());$("#cp").remove();$("body").append("<div id='cp' title='"+bb_t_col+'\' style=\'display:none\'><br /><iframe width="154" height="104" src="'+dle_root+"templates/"+dle_skin+'/bbcodes/color.html" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></div>');$("#cp").dialog({autoOpen:!0,dialogClass:"modalfixed",width:180});
$(".modalfixed.ui-dialog").css({position:"fixed"});$("#cp").dialog("option","position",["0","0"])}function setColor(a){doInsert("[color="+a+"]","[/color]",!0);$("#cp").dialog("close")}
function ins_emo(){document.getElementById(selField).focus();is_ie&&(document.getElementById(selField).focus(),ie_range_cache=document.selection.createRange());$("#dle_emo").remove();$("body").append("<div id='dle_emo' title='"+bb_t_emo+"' style='display:none'>"+document.getElementById("dle_emos").innerHTML+"</div>");var a="300",b="auto";$("#dle_emos").width()>=450&&($("#dle_emos").width(450),a="505");$("#dle_emos").height()>=300&&($("#dle_emos").height(300),b="340");$("#dle_emo").dialog({autoOpen:!0,
dialogClass:"modalfixed",width:a,height:b});$(".modalfixed.ui-dialog").css({position:"fixed"});$("#dle_emo").dialog("option","position",["0","0"])}function dle_smiley(a){doInsert(" "+a+" ","",!1);$("#dle_emo").dialog("close");ie_range_cache=null}function pagelink(){var a=get_sel(eval("fombj."+selField));a||(a=text_pages);DLEprompt(text_enter_page,"1",dle_prompt,function(b){DLEprompt(text_enter_page_name,a,dle_prompt,function(a){doInsert("[page="+b+"]"+a+"[/page]","",!1);ie_range_cache=null})})}
function translit(){var a=eval("fombj."+selField);if(ua_vers>=4&&is_ie&&is_win)if(a.isTextEdit){a.focus();var b=document.selection,d=b.createRange();if((b.type=="Text"||b.type=="None")&&d!=null)d.text=dotranslate(d.text)}else a.value=dotranslate(a.value);else a.value=dotranslate(a.value);a.focus()}
function dotranslate(a){var b="",d=0,d="",c=1;for(kk=0;kk<a.length;kk++){d=a.substr(kk,1);if(d=="["||d=="<")c=0;if(d=="]"||d==">")c=1;d=c?transsymbtocyr(b.substr(b.length-1,1),d):b.substr(b.length-1,1)+d;b=b.substr(0,b.length-1)+d}return b}function transsymbtocyr(a,b){var d=a+b,c=b.charCodeAt(0);if(!(c>=65&&c<=123||c==35||c==39))return d;for(c=0;c<lat_lr2.length;c++)if(lat_lr2[c]==d)return rus_lr2[c];for(c=0;c<lat_lr1.length;c++)if(lat_lr1[c]==b)return a+rus_lr1[c];return d}
function insert_font(a,b){if(a!=0)doInsert("["+b+"="+a+"]","[/"+b+"]",!0),fombj.bbfont.selectedIndex=0,fombj.bbsize.selectedIndex=0}function get_sel(a){if(document.selection){if(is_ie&&(document.getElementById(selField).focus(),ie_range_cache=document.selection.createRange()),a=document.selection.createRange(),a.text)return a.text}else if(typeof a.selectionStart=="number"&&a.selectionStart!=a.selectionEnd){var b=a.selectionStart;return a.value.substr(b,a.selectionEnd-b)}return!1};